kind: ExternalService
name: itemist
spec:
  env:
    - hidden: false
      name: PORT
      secret: port
    - hidden: false
      name: BASE_URL
      secret: base-url
    - hidden: false
      name: FRONTEND_URL
      secret: frontend-url
  image_pull_policy: Always
  image: itemist:<tag>
  port: 4000
  source:
    context: ../.
    node_version: '12'
    project_type: nodejs
