kind: ExternalService
name: itemist
spec:
  domains:
    - name: api.itemist.ir
  env:
    - hidden: false
      name: PORT
      secret: port
    - hidden: false
      name: BASE_URL
      secret: base-url
    - hidden: false
      name: FRONTEND_URL
      secret: frontend-url
    - hidden: false
      name: NODE_ENV
      secret: node-env
    - hidden: true
      name: SECRET_KEY
      secret: secret-key
    - hidden: true
      name: STEAM_API_KEY
      secret: steam-api-key
    - hidden: true
      name: STEAM_ACCOUNT_NAME
      secret: steam-account-name
    - hidden: true
      name: STEAM_ACCOUNT_PASSWORD
      secret: steam-account-password
    - hidden: true
      name: STEAM_ACCOUNT_SHARED_SECRET
      secret: steam-account-shared-secret
    - hidden: true
      name: STEAM_ACCOUNT_IDENTITY_SECRET
      secret: steam-account-identity-secret
    - hidden: true
      name: MONGO_URI
      secret: mongo-uri
    - hidden: true
      name: SENTRY_DSN
      secret: sentry-dsn
    - hidden: false
      name: FRONTEND_PAYMENT_CALLBACK
      secret: frontend-payment-callback
    - hidden: true
      name: ZARINPAL_MERCHANT
      secret: zarinpal-merchant
    - hidden: false
      name: CORS_WHITELIST
      secret: cors-whitelist
    - hidden: false
      name: VERIFY_PAYMENT_CALLBACK_URL
      secret: verify-payment-callback-url

  image_pull_policy: Always
  image: itemist:test-enable-payment.1
  port: 4000
  source:
    context: ../.
    node_version: '12'
    project_type: nodejs
