kind: ExternalService
name: itemist
spec:
  domains:
    - name: api.itemist.ir
  env:
    - hidden: false
      name: PORT
      secret: port
    - hidden: false
      name: BASE_URL
      secret: base-url
    - hidden: false
      name: FRONTEND_URL
      secret: frontend-url
    - hidden: false
      name: NODE_ENV
      secret: node-env
  image_pull_policy: Always
  image: itemist:v0.1.0-alpha2
  port: 4000
  source:
    context: ../.
    node_version: '12'
    project_type: nodejs
