name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm ci
          npm run build
      - uses: actions/checkout@v2
      - name: Test
        run: |
          cp .dev.template .dev
          npm ci
          npm run test
