name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: fandogh deploy
        run: |
          pip install fandogh-cli --upgrade
          fandogh login --username ${{ secrets.FANDOGH_USERNAME }} --password ${{ secrets.FANDOGH_PASSWORD }}
