name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: deploy action step
        uses: Glyphack/fandogh-service-deploy-action@v0.1.0-beta.1
        with:
          username: ${{ secrets.FANDOGH_USERNAME }}
          password: ${{ secrets.FANDOGH_PASSWORD }}
          image_name: itemist
          image_version: v0.1.0-alpha10
          path_to_service_file: ./manifests/service.yml
